[200~                                                                              InstanceSecurityGroup:

      Type: 'AWS::EC2::SecurityGroup'

                  Properties:

                                      GroupName: !Join [ "-", [ !Ref EnvironmentName, 'ec2-security-group' ] ]

                                                                  GroupDescription: Enable SSH access via port 22

                                                                                                      SecurityGroupIngress:

                                                                                                                                                    - IpProtocol: tcp

                                                                                                                                                                                                              FromPort: '22'

                                                                                                                                                                                                                                                                                    ToPort: '22'



